import { Inter } from "next/font/google";
import Topo from "@/components/topo";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "index, follow",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Topo />
        
        {children}
        
      </body>
    </html>
  );
}
