import Head from "next/head";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Introdução ao react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.container}>
        <header>
          <p>Reacj JS</p>
        </header>

        <main>
          <section className={styles.title}>
            <h1>React js</h1>
            <p>Biblioteca javascript para criar SPAs</p>
            <a href="#">Site oficial</a>
          </section>

          <section className={styles.requisitos}>
            <h2>Requisitos</h2>
            <p>Veja abaixo os requisitos minimos para se aprender react JS</p>
            <div>
              <div>
                <h3>HTML</h3>
                <p>Aprenda a estruturar os elementos da página com HTML</p>
              </div>
              <div>
                <h3>css</h3>
                <p>Aprenda a estilizar os elementos da página com CSS</p>
              </div>
              <div>
                <h3>JavaScript</h3>
                <p>Aprenda a linguagem utilizada pelo react, o JavaScript</p>
              </div>
            </div>
          </section>
        </main>

        <footer>
          <p>desenvolvido por Hydrah Tech</p>
        </footer>
      </div>
    </>
  );
}
